name: NoDropItem
version: 0.3
description: NoDropItem
author: judgetread
authors: [judgetread] 
website: http://github.com/NoDropItem
main: main.java.com.github.judgetread.NoDropItem.NoDropItem
commands:
   nodropitem:
      description: Saves players inventory on death.
      aliases: [ndi]